language: python

python:
  - "pypy3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls
  - pip install coverage
  - pip install nose

script:
  - python setup.py install
  - python setup.py nosetests --with-coverage

after_success:
  - coveralls
